### ISSUE TITLE
Lab 2 Part 2 issue

### ISSUE THREAD

**Issue by jacobtnyoung** [DS4PS/cpp-524-sum-2021#6]
The link to Yellowdig on Lab 2 Part 2 is not directing me to Yellowdig. Also, the Yellowdig link on the header of the syllabus page working. It goes to Canvas, and the Canvas Yellowdig link is not working. It is returning the error "Couldn't find valid settings for this link".

**Comment by lecy** [comment]
Technical problems - looks like YellowDig just rolled out their new platform and it broke some of the functions on Canvas. 

Please try it now. If it is still not working then I'll talk to the Ed Plus contact because they configure the settings for external tools. 

Thanks!

**Comment by jacobtnyoung** [comment]
Works now. Thanks!
